# AppSettings -- one single row holding system-wide settings. Right now
# that's just the current registration code (see the Add New User screen's
# "Generate a Registration Code" panel) -- previously this was a fixed,
# unchangeable value in auth/routes.py; now it's real and can genuinely be
# regenerated by an Admin.
import secrets
from typing import Optional
from sqlmodel import SQLModel, Field, Session, select

DEFAULT_REGISTRATION_CODE = "INFRACRACK2026"


class AppSettings(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    registration_code: str = DEFAULT_REGISTRATION_CODE


def get_settings(session: Session) -> AppSettings:
    """Get the single settings row, creating it (with the original fixed
    code, so nothing breaks for existing accounts) the first time it's
    needed."""
    settings = session.exec(select(AppSettings)).first()
    if not settings:
        settings = AppSettings()
        session.add(settings)
        session.commit()
        session.refresh(settings)
    return settings


def generate_registration_code() -> str:
    """A new, random registration code in the same ICN-XXXX-XXXX shape
    shown in the real Figma design."""
    alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"  # no 0/O/1/I -- easy to read aloud
    part1 = "".join(secrets.choice(alphabet) for _ in range(4))
    part2 = "".join(secrets.choice(alphabet) for _ in range(4))
    return f"ICN-{part1}-{part2}"
